commerce_payment.commerce_payment_gateway.plugin.payone:
  type: commerce_payment_gateway_configuration
  mapping:
    payone_mode:
      type: string
      label: 'Mode'
    payone_merchant_id:
      type: string
      label: 'Merchant ID'
    payone_portal_id:
      type: string
      label: 'Portal ID'
    payone_sub_account_id:
      type: string
      label: 'Sub-Account ID'
    payone_key:
      type: string
      label: 'PAYONE Key'
    payone_reference_prefix:
      type: string
      label: 'Reference prefix'
